### ISSUE TITLE
Criação de pipeline de CI de validação do modulo

### ISSUE THREAD

**Issue by lipenodias** [mentoriaiac/iac-modulo-groundwork-oci#6]
### Feature Request

Criação de pipeline de CI de validação do modulo

### DoD

[ ] O pipeline deve ter um teste de lint simples
[ ] O pipeline deve usar o [tfsec](https://github.com/aquasecurity/tfsec)

[Um exemplo](https://github.com/mentoriaiac/iac-modulo-compute-gcp/blob/main/.github/workflows/ci.yml) que pode ser seguido.

**Comment by gomex** [comment]
Não precisamos mais dessa tarefa, pois vamos centralizar o pipeline!
